mutation updateStats ($id: ID!, $name: String!, $GamerTag: String!, $KD: String!, $Platform: String!) {
  updateStats(
    id: $id,
    category: $category,
    name: $name, 
    constellation: $GamerTag,
    nameOrigin: $KD,
    distance: $Platform
  ) {
    id,
    name,
    GamerTag,
    KD,
    Platform,
  }
}
