mutation updateStats ($id: ID!, $name: String!, $GamerTag: String!, $KD: String!, $Platform: String!) {
  updateStats(
    id: $id,
    name: $name, 
    GamerTag: $GamerTag,
    KD: $KD,
    Platform: $Platform
  ) {
    id,
    name,
    GamerTag,
    KD,
    Platform,
  }
}
